import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resendApiKey = Deno.env.get('RESEND_API_KEY');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    if (!resendApiKey) {
      throw new Error('RESEND_API_KEY is not configured');
    }

    const { email, html, productName } = await req.json();

    if (!email || !html) {
      throw new Error('Email and HTML content are required');
    }

    console.log('Sending preview email to:', email);

    const resend = new Resend(resendApiKey);

    const emailResponse = await resend.emails.send({
      from: "Vivid AI Payments <noreply@resend.dev>",
      to: [email],
      subject: `Your ${productName} Payment Page Preview`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>Your Payment Page Preview</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 600px;
              margin: 0 auto;
              padding: 20px;
              background-color: #f8fafc;
            }
            .header {
              background: linear-gradient(135deg, #6A57FF, #00DAB5);
              color: white;
              padding: 30px 20px;
              border-radius: 12px;
              text-align: center;
              margin-bottom: 30px;
            }
            .header h1 {
              margin: 0;
              font-size: 28px;
              font-weight: 700;
            }
            .header p {
              margin: 10px 0 0 0;
              opacity: 0.9;
              font-size: 16px;
            }
            .content {
              background: white;
              padding: 30px;
              border-radius: 12px;
              box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
              margin-bottom: 20px;
            }
            .preview-container {
              border: 2px solid #e2e8f0;
              border-radius: 8px;
              padding: 20px;
              margin: 20px 0;
              background-color: #f8fafc;
            }
            .footer {
              text-align: center;
              color: #64748b;
              font-size: 14px;
              margin-top: 30px;
            }
            .footer a {
              color: #6A57FF;
              text-decoration: none;
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🎉 Your Payment Page is Ready!</h1>
            <p>Here's the preview of your "${productName}" landing page</p>
          </div>
          
          <div class="content">
            <h2>Hi there!</h2>
            <p>Your AI-generated payment page for <strong>${productName}</strong> is ready! Below is the complete HTML that you can use to create your payment page.</p>
            
            <p><strong>What's included:</strong></p>
            <ul>
              <li>✅ Mobile-responsive design</li>
              <li>✅ SEO-optimized HTML</li>
              <li>✅ Instagram carousel-style layout</li>
              <li>✅ Vivid Money branding</li>
              <li>✅ Conversion-optimized copy</li>
            </ul>

            <div class="preview-container">
              <h3>📄 Your Generated HTML:</h3>
              <p><em>The complete HTML code for your payment page is included below. You can copy and save this to use on your website or hosting platform.</em></p>
            </div>
          </div>

          <div style="background: white; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); margin: 20px 0;">
            ${html}
          </div>

          <div class="footer">
            <p>Generated by <a href="#">Vivid AI Payments</a></p>
            <p>Need help? Contact our support team</p>
          </div>
        </body>
        </html>
      `,
    });

    console.log('Email sent successfully:', emailResponse);

    return new Response(JSON.stringify({ 
      success: true,
      messageId: emailResponse.data?.id 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in send-preview-email function:', error);
    return new Response(JSON.stringify({ 
      error: error.message,
      success: false 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});