// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ympfxxxhiippgtioozky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltcGZ4eHhoaWlwcGd0aW9vemt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjM5MDIsImV4cCI6MjA2NzQ5OTkwMn0.j-kWs17fgWJgh0CXv_9CVlqpT35CtgjKHrodl_gSbJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});